import {
  FACTORY_GIT_BRANCH_ID,
  FACTORY_GIT_REPO_ID,
  FACTORY_GIT_WORKTREE_ID,
} from "../factories/git";
import { FACTORY_REPO_DEFAULT_PROJECT_ID } from "../factories/project";

export const GIT_TEST_REPO_ID = FACTORY_GIT_REPO_ID;
export const GIT_TEST_WORKTREE_ID = FACTORY_GIT_WORKTREE_ID;
export const GIT_TEST_BRANCH_ID = FACTORY_GIT_BRANCH_ID;
export const GIT_TEST_DEFAULT_PROJECT_ID = FACTORY_REPO_DEFAULT_PROJECT_ID;
