// Code generated by @tiptap/cli. DO NOT EDIT.
// Hamix does not mount this Cloud-collab NotionEditor. Prompt authoring
// uses RichPromptEditor (Hamix Notion-like surface, no room / AI token).

export type NotionEditorProps = {
  room?: string
  placeholder?: string
}

export function NotionEditor(_props: NotionEditorProps): never {
  throw new Error(
    "Do not mount stock NotionEditor. Use RichPromptEditor.",
  )
}
