package checklist_test

import (
	"context"
	"encoding/json"
	"github.com/AlexsanderHamir/Hamix/internal/handlertest"
	taskcoredomain "github.com/AlexsanderHamir/Hamix/pkgs/taskcore/domain"
	taskcorestore "github.com/AlexsanderHamir/Hamix/pkgs/taskcore/store"
	"io"
	"net/http"
	"strings"
	"testing"
	"time"
)

func TestHTTP_postChecklistItem_201ResponseShape(t *testing.T) {
	srv := handlertest.NewCreateServer(t)
	defer srv.Close()

	taskID := handlertest.MustCreateChecklistTask(t, srv, "chk-shape")

	res, err := http.Post(srv.URL+"/tasks/"+taskID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"first criterion"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, err := io.ReadAll(res.Body)
	if err != nil {
		t.Fatal(err)
	}
	if res.StatusCode != http.StatusCreated {
		t.Fatalf("status %d (want 201) body=%s", res.StatusCode, raw)
	}

	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		t.Fatalf("decode: %v body=%s", err, raw)
	}
	wantKeys := map[string]struct{}{"id": {}, "task_id": {}, "sort_order": {}, "text": {}}
	for k := range wantKeys {
		if _, ok := top[k]; !ok {
			t.Errorf("POST checklist 201 missing key %q (docs/api.md): %s", k, raw)
		}
	}
	for k := range top {
		if _, ok := wantKeys[k]; !ok {
			t.Errorf("POST checklist 201 unexpected key %q (docs/api.md): %s", k, raw)
		}
	}

	var row struct {
		ID        string `json:"id"`
		TaskID    string `json:"task_id"`
		SortOrder int    `json:"sort_order"`
		Text      string `json:"text"`
	}
	if err := json.Unmarshal(raw, &row); err != nil {
		t.Fatalf("decode envelope: %v", err)
	}
	if row.ID == "" {
		t.Error("id must not be empty")
	}
	if row.TaskID != taskID {
		t.Errorf("task_id=%q want %q", row.TaskID, taskID)
	}
	if row.SortOrder < 1 {
		t.Errorf("sort_order=%d want >=1", row.SortOrder)
	}
	if row.Text != "first criterion" {
		t.Errorf("text=%q want %q", row.Text, "first criterion")
	}
}

// TestHTTP_postChecklistItem_textRequired pins the documented 400 string for
// POST when text is missing or whitespace-only. Wording differs from PATCH's
// `text required` because the message is generated by the store, not the handler.
func TestHTTP_postChecklistItem_textRequired(t *testing.T) {
	srv := handlertest.NewCreateServer(t)
	defer srv.Close()
	taskID := handlertest.MustCreateChecklistTask(t, srv, "chk-empty")

	bodies := []struct {
		name string
		body string
	}{
		{"emptyText", `{"text":""}`},
		{"whitespaceText", `{"text":"   "}`},
	}
	for _, tc := range bodies {
		t.Run(tc.name, func(t *testing.T) {
			res, err := http.Post(srv.URL+"/tasks/"+taskID+"/checklist/items", "application/json",
				strings.NewReader(tc.body))
			if err != nil {
				t.Fatal(err)
			}
			defer res.Body.Close()
			raw, _ := io.ReadAll(res.Body)
			if res.StatusCode != http.StatusBadRequest {
				t.Fatalf("status %d (want 400) body=%s", res.StatusCode, raw)
			}
			var errBody handlertest.JSONErrorBody
			if err := json.Unmarshal(raw, &errBody); err != nil {
				t.Fatalf("decode: %v body=%s", err, raw)
			}
			if errBody.Error != "checklist text required" {
				t.Fatalf("error=%q want %q (docs/api.md)", errBody.Error, "checklist text required")
			}
		})
	}
}

// TestHTTP_postChecklistItem_rejectsRunningTask pins 409 when the task is
// in progress — criteria are locked while the agent is working.
func TestHTTP_postChecklistItem_rejectsRunningTask(t *testing.T) {
	srv, st := handlertest.NewCreateServerWithStore(t)
	defer srv.Close()
	ctx := context.Background()
	tsk, err := st.Create(ctx, taskcorestore.CreateTaskInput{
		Title: "running", Priority: taskcoredomain.PriorityMedium, Status: taskcoredomain.StatusRunning,
	}, taskcoredomain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.Post(srv.URL+"/tasks/"+tsk.ID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"late criterion"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusConflict {
		t.Fatalf("status %d (want 409) body=%s", res.StatusCode, raw)
	}
	var errBody handlertest.JSONErrorBody
	if err := json.Unmarshal(raw, &errBody); err != nil {
		t.Fatalf("decode: %v body=%s", err, raw)
	}
	if !strings.Contains(errBody.Error, "cannot change criteria while task is running") {
		t.Fatalf("error=%q want substring about running", errBody.Error)
	}
}

func TestHTTP_postChecklistItem_allowsDoneTask(t *testing.T) {
	srv, st := handlertest.NewCreateServerWithStore(t)
	defer srv.Close()
	ctx := context.Background()
	tsk, err := st.Create(ctx, taskcorestore.CreateTaskInput{
		Title: "done", Priority: taskcoredomain.PriorityMedium, Status: taskcoredomain.StatusDone,
	}, taskcoredomain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.Post(srv.URL+"/tasks/"+tsk.ID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"post-done criterion"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusCreated {
		t.Fatalf("status %d (want 201) body=%s", res.StatusCode, raw)
	}
}

// TestHTTP_patchChecklistItem_doneAgentReturnsItemsView pins the documented PATCH
// happy path for `done`: 200 + full `{ "items": [...] }` with `done:true` on the
// targeted item. This complements the existing 400 coverage in
// handler_http_checklist_test.go by locking down the success-shape side.
func TestHTTP_checklist_404OnUnknownTask(t *testing.T) {
	srv := handlertest.NewCreateServer(t)
	defer srv.Close()

	const ghost = "11111111-1111-4111-8111-111111111111"
	const ghostItem = "22222222-2222-4222-8222-222222222222"

	cases := []struct {
		name string
		req  func() (*http.Response, error)
	}{
		{"POST", func() (*http.Response, error) {
			return http.Post(srv.URL+"/tasks/"+ghost+"/checklist/items", "application/json",
				strings.NewReader(`{"text":"x"}`))
		}},
		{"PATCH", func() (*http.Response, error) {
			req, _ := http.NewRequest(http.MethodPatch,
				srv.URL+"/tasks/"+ghost+"/checklist/items/"+ghostItem,
				strings.NewReader(`{"text":"x"}`))
			req.Header.Set("Content-Type", "application/json")
			return http.DefaultClient.Do(req)
		}},
		{"DELETE", func() (*http.Response, error) {
			req, _ := http.NewRequest(http.MethodDelete,
				srv.URL+"/tasks/"+ghost+"/checklist/items/"+ghostItem, nil)
			return http.DefaultClient.Do(req)
		}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res, err := tc.req()
			if err != nil {
				t.Fatal(err)
			}
			defer res.Body.Close()
			if res.StatusCode != http.StatusNotFound {
				body, _ := io.ReadAll(res.Body)
				t.Fatalf("status %d (want 404) body=%s", res.StatusCode, body)
			}
		})
	}
}

// TestHTTP_postChecklistItem_publishesTaskUpdated colocates the per-route SSE
// positive invariant from sse_trigger_surface_test.go with the rest of this
// route's contract: a successful POST publishes exactly `task_updated:{id}`
// (and nothing else). Subscribing AFTER seed avoids draining the task_created
// frame from the seed task. Mirrors Sessions 14–17's per-route SSE pin pattern.
func TestHTTP_postChecklistItem_publishesTaskUpdated(t *testing.T) {
	srv, _, hub := handlertest.NewSSETriggerServer(t)
	defer srv.Close()
	taskID := handlertest.MustCreateChecklistTask(t, srv, "chk-sse-pos")

	ch, unsub := hub.Subscribe()
	defer unsub()

	res, err := http.Post(srv.URL+"/tasks/"+taskID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"sse positive"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusCreated {
		t.Fatalf("status %d (want 201) body=%s", res.StatusCode, raw)
	}

	events := handlertest.DrainSSE(t, ch, 1, 2*time.Second)
	got := handlertest.SummarizeSSEEvents(events)
	handlertest.MustEqualEvents(t, "POST /tasks/{id}/checklist/items", got, []string{"task_updated:" + taskID})
	handlertest.MustHaveTaskUpdatedData(t, "POST /tasks/{id}/checklist/items", events, taskID)
}

// TestHTTP_postChecklistItem_errorPathsNeverPublish pins the negative-side SSE
// invariant: 400 (text required, whitespace text, inheriting child) and 404
// (unknown task) must never publish on the SSE hub. Without this pin a future
// refactor that moved `notifyChange` above the error-write branch in
// `postChecklistItem` would silently leak ghost `task_updated` frames to clients.
func TestHTTP_postChecklistItem_errorPathsNeverPublish(t *testing.T) {
	srv, _, hub := handlertest.NewSSETriggerServer(t)
	defer srv.Close()
	parentID := handlertest.MustCreateChecklistTask(t, srv, "chk-sse-neg-parent")

	ch, unsub := hub.Subscribe()
	defer unsub()

	cases := []struct {
		name   string
		taskID string
		body   string
		want   int
	}{
		{"emptyText", parentID, `{"text":""}`, http.StatusBadRequest},
		{"whitespaceText", parentID, `{"text":"   "}`, http.StatusBadRequest},
		{"unknownTask", "11111111-1111-4111-8111-111111111111", `{"text":"x"}`, http.StatusNotFound},
	}
	for _, tc := range cases {
		res, err := http.Post(srv.URL+"/tasks/"+tc.taskID+"/checklist/items", "application/json",
			strings.NewReader(tc.body))
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		raw, _ := io.ReadAll(res.Body)
		_ = res.Body.Close()
		if res.StatusCode != tc.want {
			t.Fatalf("%s: status %d (want %d) body=%s", tc.name, res.StatusCode, tc.want, raw)
		}
	}

	got := handlertest.SummarizeSSEEvents(handlertest.DrainSSE(t, ch, 0, 200*time.Millisecond))
	if len(got) != 0 {
		t.Fatalf("drained SSE events %v after POST checklist error round-trips; want zero (400/404 paths must never publish)", got)
	}
}

// TestHTTP_patchChecklistItem_textBranch400Strings pins the bare wire
// phrases for every PATCH text-update branch validation 400 documented in
// docs/api.md. The done-branch wire phrases (`only the agent may mark
// checklist items done or undone`, `done` value typing) are pinned by the
// existing happy-path file (handler_http_checklist_test.go); this test
// closes the analogous gap for the text branch (`text required`,
// `cannot update inherited checklist definitions from this task`) and the
// shared one-of-choice phrase (`send exactly one of text or done`) so the
// bare phrases live next to the per-route SSE pins added in Session 19.
// Without it a future copy-edit in handler_checklist.go (handler-generated
// "text required" + "send exactly one of text or done") or
// pkgs/tasks/store/internal/checklist/checklist.go (store-generated
// "cannot update inherited checklist definitions from this task") would
// silently drift the wire phrase clients rely on for error UI without
// breaking any contract test. Mirrors the bare-phrase tables in
// handler_http_events_patch_contract_test.go (Session 17) and the POST
// `text required` table above (Session 4).
