package handler

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"testing"
	"time"

	"github.com/AlexsanderHamir/Hamix/pkgs/tasks/domain"
	"github.com/AlexsanderHamir/Hamix/pkgs/tasks/store"
)

// TestHTTP_postChecklistItem_201ResponseShape pins the documented POST 201
// envelope: the bare `domain.TaskChecklistItem` JSON `{id, task_id, sort_order, text}`.
// This is intentionally **not** the same shape as items in `GET /tasks/{id}/checklist`
// (no `done`, includes `task_id`); the doc table calls this asymmetry out so
// future struct changes that drift either way fail loudly.
func TestHTTP_postChecklistItem_201ResponseShape(t *testing.T) {
	srv := newTaskCreateTestServer(t)
	defer srv.Close()

	taskID := mustCreateChecklistTask(t, srv, "chk-shape")

	res, err := http.Post(srv.URL+"/tasks/"+taskID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"first criterion"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, err := io.ReadAll(res.Body)
	if err != nil {
		t.Fatal(err)
	}
	if res.StatusCode != http.StatusCreated {
		t.Fatalf("status %d (want 201) body=%s", res.StatusCode, raw)
	}

	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		t.Fatalf("decode: %v body=%s", err, raw)
	}
	wantKeys := map[string]struct{}{"id": {}, "task_id": {}, "sort_order": {}, "text": {}}
	for k := range wantKeys {
		if _, ok := top[k]; !ok {
			t.Errorf("POST checklist 201 missing key %q (docs/api.md): %s", k, raw)
		}
	}
	for k := range top {
		if _, ok := wantKeys[k]; !ok {
			t.Errorf("POST checklist 201 unexpected key %q (docs/api.md): %s", k, raw)
		}
	}

	var row struct {
		ID        string `json:"id"`
		TaskID    string `json:"task_id"`
		SortOrder int    `json:"sort_order"`
		Text      string `json:"text"`
	}
	if err := json.Unmarshal(raw, &row); err != nil {
		t.Fatalf("decode envelope: %v", err)
	}
	if row.ID == "" {
		t.Error("id must not be empty")
	}
	if row.TaskID != taskID {
		t.Errorf("task_id=%q want %q", row.TaskID, taskID)
	}
	if row.SortOrder < 1 {
		t.Errorf("sort_order=%d want >=1", row.SortOrder)
	}
	if row.Text != "first criterion" {
		t.Errorf("text=%q want %q", row.Text, "first criterion")
	}
}

// TestHTTP_postChecklistItem_textRequired pins the documented 400 string for
// POST when text is missing or whitespace-only. Wording differs from PATCH's
// `text required` because the message is generated by the store, not the handler.
func TestHTTP_postChecklistItem_textRequired(t *testing.T) {
	srv := newTaskCreateTestServer(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-empty")

	bodies := []struct {
		name string
		body string
	}{
		{"emptyText", `{"text":""}`},
		{"whitespaceText", `{"text":"   "}`},
	}
	for _, tc := range bodies {
		t.Run(tc.name, func(t *testing.T) {
			res, err := http.Post(srv.URL+"/tasks/"+taskID+"/checklist/items", "application/json",
				strings.NewReader(tc.body))
			if err != nil {
				t.Fatal(err)
			}
			defer res.Body.Close()
			raw, _ := io.ReadAll(res.Body)
			if res.StatusCode != http.StatusBadRequest {
				t.Fatalf("status %d (want 400) body=%s", res.StatusCode, raw)
			}
			var errBody jsonErrorBody
			if err := json.Unmarshal(raw, &errBody); err != nil {
				t.Fatalf("decode: %v body=%s", err, raw)
			}
			if errBody.Error != "checklist text required" {
				t.Fatalf("error=%q want %q (docs/api.md)", errBody.Error, "checklist text required")
			}
		})
	}
}

// TestHTTP_postChecklistItem_rejectsRunningTask pins 409 when the task is
// in progress — criteria are locked while the agent is working.
func TestHTTP_postChecklistItem_rejectsRunningTask(t *testing.T) {
	srv, st := newTaskCreateTestServerWithStore(t)
	defer srv.Close()
	ctx := context.Background()
	tsk, err := st.Create(ctx, store.CreateTaskInput{
		Title: "running", Priority: domain.PriorityMedium, Status: domain.StatusRunning,
	}, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.Post(srv.URL+"/tasks/"+tsk.ID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"late criterion"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusConflict {
		t.Fatalf("status %d (want 409) body=%s", res.StatusCode, raw)
	}
	var errBody jsonErrorBody
	if err := json.Unmarshal(raw, &errBody); err != nil {
		t.Fatalf("decode: %v body=%s", err, raw)
	}
	if !strings.Contains(errBody.Error, "cannot change criteria while task is running") {
		t.Fatalf("error=%q want substring about running", errBody.Error)
	}
}

func TestHTTP_postChecklistItem_allowsDoneTask(t *testing.T) {
	srv, st := newTaskCreateTestServerWithStore(t)
	defer srv.Close()
	ctx := context.Background()
	tsk, err := st.Create(ctx, store.CreateTaskInput{
		Title: "done", Priority: domain.PriorityMedium, Status: domain.StatusDone,
	}, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.Post(srv.URL+"/tasks/"+tsk.ID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"post-done criterion"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusCreated {
		t.Fatalf("status %d (want 201) body=%s", res.StatusCode, raw)
	}
}

// TestHTTP_patchChecklistItem_doneAgentReturnsItemsView pins the documented PATCH
// happy path for `done`: 200 + full `{ "items": [...] }` with `done:true` on the
// targeted item. This complements the existing 400 coverage in
// handler_http_checklist_test.go by locking down the success-shape side.
func TestHTTP_patchChecklistItem_doneAgentReturnsItemsView(t *testing.T) {
	srv, st := newTaskCreateTestServerWithStore(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-done")
	it, err := st.AddChecklistItem(context.Background(), taskID, "review", nil, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}

	req, err := http.NewRequest(http.MethodPatch,
		srv.URL+"/tasks/"+taskID+"/checklist/items/"+it.ID,
		strings.NewReader(`{"done":true,"evidence":"reviewed in test","verified_by":"agent_self"}`))
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Actor", "agent")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusOK {
		t.Fatalf("status %d (want 200) body=%s", res.StatusCode, raw)
	}

	var top map[string]json.RawMessage
	if err := json.Unmarshal(raw, &top); err != nil {
		t.Fatalf("decode: %v body=%s", err, raw)
	}
	if _, ok := top["items"]; !ok || len(top) != 1 {
		t.Fatalf("PATCH 200 must return only `items`; got keys=%v body=%s", keysOf(top), raw)
	}
	var out struct {
		Items []struct {
			ID         string `json:"id"`
			SortOrder  int    `json:"sort_order"`
			Text       string `json:"text"`
			Done       bool   `json:"done"`
			Evidence   string `json:"evidence"`
			VerifiedBy string `json:"verified_by"`
		} `json:"items"`
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatalf("decode items: %v", err)
	}
	if len(out.Items) != 2 {
		t.Fatalf("items len=%d want 2", len(out.Items))
	}
	var got *struct {
		ID         string `json:"id"`
		SortOrder  int    `json:"sort_order"`
		Text       string `json:"text"`
		Done       bool   `json:"done"`
		Evidence   string `json:"evidence"`
		VerifiedBy string `json:"verified_by"`
	}
	for i := range out.Items {
		if out.Items[i].ID == it.ID {
			got = &out.Items[i]
			break
		}
	}
	if got == nil {
		t.Fatalf("patched item missing from %#v", out.Items)
	}
	if got.Text != "review" || !got.Done {
		t.Fatalf("item=%+v want id=%s text=review done=true", got, it.ID)
	}
}

// TestHTTP_deleteChecklistItem_204ThenGone pins the documented DELETE happy
// path: 204 with empty body and the row vanishing from a follow-up GET.
func TestHTTP_deleteChecklistItem_204ThenGone(t *testing.T) {
	srv, st := newTaskCreateTestServerWithStore(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-del")
	it, err := st.AddChecklistItem(context.Background(), taskID, "remove me", nil, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}

	req, err := http.NewRequest(http.MethodDelete,
		srv.URL+"/tasks/"+taskID+"/checklist/items/"+it.ID, nil)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	body, _ := io.ReadAll(res.Body)
	_ = res.Body.Close()
	if res.StatusCode != http.StatusNoContent {
		t.Fatalf("status %d (want 204) body=%s", res.StatusCode, body)
	}
	if len(body) != 0 {
		t.Fatalf("DELETE 204 body must be empty, got %q", body)
	}

	getRes, err := http.Get(srv.URL + "/tasks/" + taskID + "/checklist")
	if err != nil {
		t.Fatal(err)
	}
	defer getRes.Body.Close()
	if getRes.StatusCode != http.StatusOK {
		t.Fatalf("GET checklist status %d", getRes.StatusCode)
	}
	var got struct {
		Items []struct {
			ID string `json:"id"`
		} `json:"items"`
	}
	if err := json.NewDecoder(getRes.Body).Decode(&got); err != nil {
		t.Fatal(err)
	}
	for _, item := range got.Items {
		if item.ID == it.ID {
			t.Fatalf("deleted item %q still present in GET checklist", it.ID)
		}
	}
}

// TestHTTP_checklist_404OnUnknownTask pins the documented 404 mapping across
// the three checklist write routes when the task id does not exist.
func TestHTTP_checklist_404OnUnknownTask(t *testing.T) {
	srv := newTaskCreateTestServer(t)
	defer srv.Close()

	const ghost = "11111111-1111-4111-8111-111111111111"
	const ghostItem = "22222222-2222-4222-8222-222222222222"

	cases := []struct {
		name string
		req  func() (*http.Response, error)
	}{
		{"POST", func() (*http.Response, error) {
			return http.Post(srv.URL+"/tasks/"+ghost+"/checklist/items", "application/json",
				strings.NewReader(`{"text":"x"}`))
		}},
		{"PATCH", func() (*http.Response, error) {
			req, _ := http.NewRequest(http.MethodPatch,
				srv.URL+"/tasks/"+ghost+"/checklist/items/"+ghostItem,
				strings.NewReader(`{"text":"x"}`))
			req.Header.Set("Content-Type", "application/json")
			return http.DefaultClient.Do(req)
		}},
		{"DELETE", func() (*http.Response, error) {
			req, _ := http.NewRequest(http.MethodDelete,
				srv.URL+"/tasks/"+ghost+"/checklist/items/"+ghostItem, nil)
			return http.DefaultClient.Do(req)
		}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			res, err := tc.req()
			if err != nil {
				t.Fatal(err)
			}
			defer res.Body.Close()
			if res.StatusCode != http.StatusNotFound {
				body, _ := io.ReadAll(res.Body)
				t.Fatalf("status %d (want 404) body=%s", res.StatusCode, body)
			}
		})
	}
}

// TestHTTP_postChecklistItem_publishesTaskUpdated colocates the per-route SSE
// positive invariant from sse_trigger_surface_test.go with the rest of this
// route's contract: a successful POST publishes exactly `task_updated:{id}`
// (and nothing else). Subscribing AFTER seed avoids draining the task_created
// frame from the seed task. Mirrors Sessions 14–17's per-route SSE pin pattern.
func TestHTTP_postChecklistItem_publishesTaskUpdated(t *testing.T) {
	srv, _, hub := newSSETriggerServer(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-sse-pos")

	ch, unsub := hub.Subscribe()
	defer unsub()

	res, err := http.Post(srv.URL+"/tasks/"+taskID+"/checklist/items", "application/json",
		strings.NewReader(`{"text":"sse positive"}`))
	if err != nil {
		t.Fatal(err)
	}
	defer res.Body.Close()
	raw, _ := io.ReadAll(res.Body)
	if res.StatusCode != http.StatusCreated {
		t.Fatalf("status %d (want 201) body=%s", res.StatusCode, raw)
	}

	events := drainSSE(t, ch, 1, 2*time.Second)
	got := summarize(events)
	mustEqualEvents(t, "POST /tasks/{id}/checklist/items", got, []string{"task_updated:" + taskID})
	mustHaveTaskUpdatedData(t, "POST /tasks/{id}/checklist/items", events, taskID)
}

// TestHTTP_postChecklistItem_errorPathsNeverPublish pins the negative-side SSE
// invariant: 400 (text required, whitespace text, inheriting child) and 404
// (unknown task) must never publish on the SSE hub. Without this pin a future
// refactor that moved `notifyChange` above the error-write branch in
// `postChecklistItem` would silently leak ghost `task_updated` frames to clients.
func TestHTTP_postChecklistItem_errorPathsNeverPublish(t *testing.T) {
	srv, _, hub := newSSETriggerServer(t)
	defer srv.Close()
	parentID := mustCreateChecklistTask(t, srv, "chk-sse-neg-parent")

	ch, unsub := hub.Subscribe()
	defer unsub()

	cases := []struct {
		name   string
		taskID string
		body   string
		want   int
	}{
		{"emptyText", parentID, `{"text":""}`, http.StatusBadRequest},
		{"whitespaceText", parentID, `{"text":"   "}`, http.StatusBadRequest},
		{"unknownTask", "11111111-1111-4111-8111-111111111111", `{"text":"x"}`, http.StatusNotFound},
	}
	for _, tc := range cases {
		res, err := http.Post(srv.URL+"/tasks/"+tc.taskID+"/checklist/items", "application/json",
			strings.NewReader(tc.body))
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		raw, _ := io.ReadAll(res.Body)
		_ = res.Body.Close()
		if res.StatusCode != tc.want {
			t.Fatalf("%s: status %d (want %d) body=%s", tc.name, res.StatusCode, tc.want, raw)
		}
	}

	got := summarize(drainSSE(t, ch, 0, 200*time.Millisecond))
	if len(got) != 0 {
		t.Fatalf("drained SSE events %v after POST checklist error round-trips; want zero (400/404 paths must never publish)", got)
	}
}

// TestHTTP_patchChecklistItem_textBranch400Strings pins the bare wire
// phrases for every PATCH text-update branch validation 400 documented in
// docs/api.md. The done-branch wire phrases (`only the agent may mark
// checklist items done or undone`, `done` value typing) are pinned by the
// existing happy-path file (handler_http_checklist_test.go); this test
// closes the analogous gap for the text branch (`text required`,
// `cannot update inherited checklist definitions from this task`) and the
// shared one-of-choice phrase (`send exactly one of text or done`) so the
// bare phrases live next to the per-route SSE pins added in Session 19.
// Without it a future copy-edit in handler_checklist.go (handler-generated
// "text required" + "send exactly one of text or done") or
// pkgs/tasks/store/internal/checklist/checklist.go (store-generated
// "cannot update inherited checklist definitions from this task") would
// silently drift the wire phrase clients rely on for error UI without
// breaking any contract test. Mirrors the bare-phrase tables in
// handler_http_events_patch_contract_test.go (Session 17) and the POST
// `text required` table above (Session 4).
func TestHTTP_patchChecklistItem_textBranch400Strings(t *testing.T) {
	srv := newTaskCreateTestServer(t)
	defer srv.Close()

	parentID := mustCreateChecklistTask(t, srv, "chk-text-400-parent")
	defRes, err := http.Post(srv.URL+"/tasks/"+parentID+"/checklist/items",
		"application/json", strings.NewReader(`{"text":"owned"}`))
	if err != nil {
		t.Fatal(err)
	}
	defBody, _ := io.ReadAll(defRes.Body)
	_ = defRes.Body.Close()
	if defRes.StatusCode != http.StatusCreated {
		t.Fatalf("seed item status %d body=%s", defRes.StatusCode, defBody)
	}
	var def domain.TaskChecklistItem
	if err := json.Unmarshal(defBody, &def); err != nil {
		t.Fatal(err)
	}

	patch := func(taskID, itemID, body string) (int, string) {
		t.Helper()
		req, err := http.NewRequest(http.MethodPatch,
			srv.URL+"/tasks/"+taskID+"/checklist/items/"+itemID,
			strings.NewReader(body))
		if err != nil {
			t.Fatal(err)
		}
		req.Header.Set("Content-Type", "application/json")
		res, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatal(err)
		}
		raw, _ := io.ReadAll(res.Body)
		_ = res.Body.Close()
		return res.StatusCode, string(raw)
	}

	cases := []struct {
		name             string
		taskID, itemID   string
		body             string
		want             string
		commentaryReason string
	}{
		{
			name: "emptyText", taskID: parentID, itemID: def.ID,
			body:             `{"text":""}`,
			want:             "text required",
			commentaryReason: "handler-generated phrase before the store call (handler_checklist.go:103); empty/whitespace-only text is rejected here so the store never sees it",
		},
		{
			name: "whitespaceText", taskID: parentID, itemID: def.ID,
			body:             `{"text":"   \t  "}`,
			want:             "text required",
			commentaryReason: "same handler branch as emptyText; trim happens before the empty check so all-whitespace produces the same wire phrase rather than being silently dropped to a store-side error",
		},
		{
			name: "noFields", taskID: parentID, itemID: def.ID,
			body:             `{}`,
			want:             "send exactly one of text, verify_commands, or done",
			commentaryReason: "shared one-of-choice phrase that gates BOTH text and done branches (handler_checklist.go:95); the existing errorPathsNeverPublish test only checks status code, so the bare phrase needs its own pin",
		},
		{
			name: "bothFields", taskID: parentID, itemID: def.ID,
			body:             `{"text":"x","done":true}`,
			want:             "send exactly one of text, verify_commands, or done",
			commentaryReason: "same one-of phrase from the opposite direction (sending both fields); proves the textSet == doneSet branch covers the symmetric case the doc bullet `or neither field was provided for the one-of choice` only covers the empty side of",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			code, raw := patch(tc.taskID, tc.itemID, tc.body)
			if code != http.StatusBadRequest {
				t.Fatalf("status %d (want 400) body=%s — case rationale: %s", code, raw, tc.commentaryReason)
			}
			var errBody jsonErrorBody
			if err := json.Unmarshal([]byte(raw), &errBody); err != nil {
				t.Fatalf("decode: %v body=%s", err, raw)
			}
			if errBody.Error != tc.want {
				t.Fatalf("error=%q want %q (docs/api.md PATCH /tasks/{id}/checklist/items/{itemId} 400 strings) — case rationale: %s", errBody.Error, tc.want, tc.commentaryReason)
			}
		})
	}
}

// TestHTTP_patchChecklistItem_publishesTaskUpdated colocates the per-route SSE
// positive invariant for PATCH: a successful done-toggle publishes exactly
// `task_updated:{id}`.
func TestHTTP_patchChecklistItem_publishesTaskUpdated(t *testing.T) {
	srv, st, hub := newSSETriggerServer(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-sse-patch")
	it, err := st.AddChecklistItem(context.Background(), taskID, "review", nil, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}

	ch, unsub := hub.Subscribe()
	defer unsub()

	req, err := http.NewRequest(http.MethodPatch,
		srv.URL+"/tasks/"+taskID+"/checklist/items/"+it.ID,
		strings.NewReader(`{"done":true,"evidence":"sse test","verified_by":"agent_self"}`))
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Actor", "agent")
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := io.ReadAll(res.Body)
	_ = res.Body.Close()
	if res.StatusCode != http.StatusOK {
		t.Fatalf("status %d (want 200) body=%s", res.StatusCode, raw)
	}

	events := drainSSE(t, ch, 1, 2*time.Second)
	got := summarize(events)
	mustEqualEvents(t, "PATCH /tasks/{id}/checklist/items/{itemId}", got, []string{"task_updated:" + taskID})
	mustHaveTaskUpdatedData(t, "PATCH /tasks/{id}/checklist/items/{itemId}", events, taskID)
}

// TestHTTP_patchChecklistItem_errorPathsNeverPublish pins the negative-side SSE
// invariant: 400 (done by user actor, unknown done value) and 404 (unknown
// task, unknown item) must never publish.
func TestHTTP_patchChecklistItem_errorPathsNeverPublish(t *testing.T) {
	srv, st, hub := newSSETriggerServer(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-sse-patch-neg")
	it, err := st.AddChecklistItem(context.Background(), taskID, "neg", nil, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}

	ch, unsub := hub.Subscribe()
	defer unsub()

	doPatch := func(name, taskID, itemID, body, actor string, want int) {
		t.Helper()
		req, err := http.NewRequest(http.MethodPatch,
			srv.URL+"/tasks/"+taskID+"/checklist/items/"+itemID,
			strings.NewReader(body))
		if err != nil {
			t.Fatal(err)
		}
		req.Header.Set("Content-Type", "application/json")
		if actor != "" {
			req.Header.Set("X-Actor", actor)
		}
		res, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		raw, _ := io.ReadAll(res.Body)
		_ = res.Body.Close()
		if res.StatusCode != want {
			t.Fatalf("%s: status %d (want %d) body=%s", name, res.StatusCode, want, raw)
		}
	}

	doPatch("doneByUser", taskID, it.ID, `{"done":true}`, "user", http.StatusBadRequest)
	doPatch("noFields", taskID, it.ID, `{}`, "agent", http.StatusBadRequest)
	doPatch("unknownTask", "11111111-1111-4111-8111-111111111111", it.ID, `{"text":"x"}`, "", http.StatusNotFound)
	doPatch("unknownItem", taskID, "22222222-2222-4222-8222-222222222222", `{"text":"x"}`, "", http.StatusNotFound)

	got := summarize(drainSSE(t, ch, 0, 200*time.Millisecond))
	if len(got) != 0 {
		t.Fatalf("drained SSE events %v after PATCH checklist error round-trips; want zero (400/404 paths must never publish)", got)
	}
}

// TestHTTP_deleteChecklistItem_publishesTaskUpdated colocates the per-route SSE
// positive invariant for DELETE: a successful removal publishes exactly
// `task_updated:{id}`.
func TestHTTP_deleteChecklistItem_publishesTaskUpdated(t *testing.T) {
	srv, st, hub := newSSETriggerServer(t)
	defer srv.Close()
	taskID := mustCreateChecklistTask(t, srv, "chk-sse-del")
	it, err := st.AddChecklistItem(context.Background(), taskID, "remove", nil, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}

	ch, unsub := hub.Subscribe()
	defer unsub()

	req, err := http.NewRequest(http.MethodDelete,
		srv.URL+"/tasks/"+taskID+"/checklist/items/"+it.ID, nil)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := io.ReadAll(res.Body)
	_ = res.Body.Close()
	if res.StatusCode != http.StatusNoContent {
		t.Fatalf("status %d (want 204) body=%s", res.StatusCode, raw)
	}

	events := drainSSE(t, ch, 1, 2*time.Second)
	got := summarize(events)
	mustEqualEvents(t, "DELETE /tasks/{id}/checklist/items/{itemId}", got, []string{"task_updated:" + taskID})
	mustHaveTaskUpdatedData(t, "DELETE /tasks/{id}/checklist/items/{itemId}", events, taskID)
}

// TestHTTP_deleteChecklistItem_errorPathsNeverPublish pins the negative-side
// SSE invariant: 400 (inheriting child) and 404 (unknown task, unknown item)
// must never publish.
func TestHTTP_deleteChecklistItem_errorPathsNeverPublish(t *testing.T) {
	srv, st, hub := newSSETriggerServer(t)
	defer srv.Close()
	parentID := mustCreateChecklistTask(t, srv, "chk-sse-del-par")
	it, err := st.AddChecklistItem(context.Background(), parentID, "owned", nil, domain.ActorUser)
	if err != nil {
		t.Fatal(err)
	}

	ch, unsub := hub.Subscribe()
	defer unsub()

	doDelete := func(name, taskID, itemID string, want int) {
		t.Helper()
		req, err := http.NewRequest(http.MethodDelete,
			srv.URL+"/tasks/"+taskID+"/checklist/items/"+itemID, nil)
		if err != nil {
			t.Fatal(err)
		}
		res, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		raw, _ := io.ReadAll(res.Body)
		_ = res.Body.Close()
		if res.StatusCode != want {
			t.Fatalf("%s: status %d (want %d) body=%s", name, res.StatusCode, want, raw)
		}
	}

	doDelete("unknownTask", "11111111-1111-4111-8111-111111111111", it.ID, http.StatusNotFound)
	doDelete("unknownItem", parentID, "22222222-2222-4222-8222-222222222222", http.StatusNotFound)

	got := summarize(drainSSE(t, ch, 0, 200*time.Millisecond))
	if len(got) != 0 {
		t.Fatalf("drained SSE events %v after DELETE checklist error round-trips; want zero (400/404 paths must never publish)", got)
	}
}

func keysOf(m map[string]json.RawMessage) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}
