// Single-file bundle for the hamix-draft-agent sidecar. esbuild is enough —
// no need for a proper bundler because the entry has one CLI shape and only a
// few deps. @cursor/sdk is left external so a broken/optional install does
// not fail the offline build; the runtime dynamic import in sdkAgentPort.ts
// surfaces missing SDK via readyz.
import { build } from "esbuild";
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const outfile = resolve(root, "dist", "hamix-draft-agent.js");

mkdirSync(dirname(outfile), { recursive: true });

const pkg = JSON.parse(
  readFileSync(resolve(root, "package.json"), "utf8"),
);

await build({
  entryPoints: [resolve(root, "src", "cli.ts")],
  outfile,
  bundle: true,
  platform: "node",
  target: "node20",
  format: "esm",
  sourcemap: false,
  minify: false,
  legalComments: "none",
  banner: {
    // esbuild preserves the shebang from src/cli.ts automatically. Do not
    // repeat it here or Node ESM rejects the "second shebang" as invalid.
    js: `// hamix-draft-agent ${pkg.version}
// Auto-generated by scripts/build.mjs; do not edit by hand.
import { createRequire as __hamixCreateRequire } from 'node:module';
const require = __hamixCreateRequire(import.meta.url);
`,
  },
  external: ["@cursor/sdk"],
});

try {
  chmodSync(outfile, 0o755);
} catch {
  // no-op on Windows
}

// Emit a tiny package.json alongside the bundle so `node dist/...` treats it
// as ESM without a top-level "type": "module".
writeFileSync(
  resolve(root, "dist", "package.json"),
  JSON.stringify({ type: "module", name: pkg.name, version: pkg.version }, null, 2),
);

// eslint-disable-next-line no-console
console.log(`built ${outfile}`);
